/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.thrudb.thrudoc;


import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;
import java.util.Map;
import java.util.HashMap;

public class ExceptionType {
  public static final int UNKNOWN = 1;
  public static final int NO_SUCH_KEY = 2;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(UNKNOWN, NO_SUCH_KEY);
  public static final Map<Integer, String> VALUES_TO_NAMES = new HashMap<Integer, String>() {{
    put(UNKNOWN, "UNKNOWN");
    put(NO_SUCH_KEY, "NO_SUCH_KEY");
  }};
}
