/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.thrudb;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import java.util.BitSet;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;

public class Thrudb {

  /**
   * Base service calls all thrudb services must implement.
   * 
   * Primarily for KPI and Replication purposes.
   * 
   */
  public interface Iface {

    /**
     *  * <pre>
     *  * Lists the names of the servers currently running
     *  * </pre>
     * list<string>      getAvailibleServers();
     * 
     * /**
     *  * <pre>
     *  * Retrieves a map of data about this service.
     *  *
     *  * There are many kinds of data:
     *  *
     *  * Service call counts -
     *  *                      All keys will start with "mc_", example: "mc_get"
     *  *                      All values will represent number of times invoked
     *  *
     *  * Service call message sizes -
     *  *                      All keys will start with "ms_"
     *  *                      All values will represent total bytes received
     *  *
     *  * Service memory/cpu usage, uptime and health -
     *  *                      key:"heap",  value:heapsize in kb
     *  *                      key:"cpu",   value:0-100 representing %cpu
     *  *                      key:"uptime",value:seconds since start
     *  *
     *  *
     *  * Note, this data is ephemeral so if the service is restarted the previous
     *  * stats are lost.</pre>
     * 
     * @param server
     */
    public Map<String,Long> getServiceStats(String server) throws TException;

    /**
     * Acts as a noop, for debug and monitoring purposes.
     */
    public void ping() throws TException;

    /**
     * <pre>Will return a number of binary requests from the redo logs.
     * 
     * @param lsn
     *            The log sequence number to start from (inclusive)
     * @param kbLimit
     *                        The max response size of the messages (not strict)</pre>
     * 
     * @param server
     * @param bucket
     * @param lsn
     * @param kbLimit
     */
    public List<logEntry> getLogSince(String server, String bucket, String lsn, int kbLimit) throws TException;

  }

  public static class Client implements Iface {
    public Client(TProtocol prot)
    {
      this(prot, prot);
    }

    public Client(TProtocol iprot, TProtocol oprot)
    {
      iprot_ = iprot;
      oprot_ = oprot;
    }

    protected TProtocol iprot_;
    protected TProtocol oprot_;

    protected int seqid_;

    public TProtocol getInputProtocol()
    {
      return this.iprot_;
    }

    public TProtocol getOutputProtocol()
    {
      return this.oprot_;
    }

    public Map<String,Long> getServiceStats(String server) throws TException
    {
      send_getServiceStats(server);
      return recv_getServiceStats();
    }

    public void send_getServiceStats(String server) throws TException
    {
      oprot_.writeMessageBegin(new TMessage("getServiceStats", TMessageType.CALL, seqid_));
      getServiceStats_args args = new getServiceStats_args();
      args.server = server;
      args.write(oprot_);
      oprot_.writeMessageEnd();
      oprot_.getTransport().flush();
    }

    public Map<String,Long> recv_getServiceStats() throws TException
    {
      TMessage msg = iprot_.readMessageBegin();
      if (msg.type == TMessageType.EXCEPTION) {
        TApplicationException x = TApplicationException.read(iprot_);
        iprot_.readMessageEnd();
        throw x;
      }
      getServiceStats_result result = new getServiceStats_result();
      result.read(iprot_);
      iprot_.readMessageEnd();
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new TApplicationException(TApplicationException.MISSING_RESULT, "getServiceStats failed: unknown result");
    }

    public void ping() throws TException
    {
      send_ping();
      recv_ping();
    }

    public void send_ping() throws TException
    {
      oprot_.writeMessageBegin(new TMessage("ping", TMessageType.CALL, seqid_));
      ping_args args = new ping_args();
      args.write(oprot_);
      oprot_.writeMessageEnd();
      oprot_.getTransport().flush();
    }

    public void recv_ping() throws TException
    {
      TMessage msg = iprot_.readMessageBegin();
      if (msg.type == TMessageType.EXCEPTION) {
        TApplicationException x = TApplicationException.read(iprot_);
        iprot_.readMessageEnd();
        throw x;
      }
      ping_result result = new ping_result();
      result.read(iprot_);
      iprot_.readMessageEnd();
      return;
    }

    public List<logEntry> getLogSince(String server, String bucket, String lsn, int kbLimit) throws TException
    {
      send_getLogSince(server, bucket, lsn, kbLimit);
      return recv_getLogSince();
    }

    public void send_getLogSince(String server, String bucket, String lsn, int kbLimit) throws TException
    {
      oprot_.writeMessageBegin(new TMessage("getLogSince", TMessageType.CALL, seqid_));
      getLogSince_args args = new getLogSince_args();
      args.server = server;
      args.bucket = bucket;
      args.lsn = lsn;
      args.kbLimit = kbLimit;
      args.write(oprot_);
      oprot_.writeMessageEnd();
      oprot_.getTransport().flush();
    }

    public List<logEntry> recv_getLogSince() throws TException
    {
      TMessage msg = iprot_.readMessageBegin();
      if (msg.type == TMessageType.EXCEPTION) {
        TApplicationException x = TApplicationException.read(iprot_);
        iprot_.readMessageEnd();
        throw x;
      }
      getLogSince_result result = new getLogSince_result();
      result.read(iprot_);
      iprot_.readMessageEnd();
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new TApplicationException(TApplicationException.MISSING_RESULT, "getLogSince failed: unknown result");
    }

  }
  public static class Processor implements TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(Iface iface)
    {
      iface_ = iface;
      processMap_.put("getServiceStats", new getServiceStats());
      processMap_.put("ping", new ping());
      processMap_.put("getLogSince", new getLogSince());
    }

    protected static interface ProcessFunction {
      public void process(int seqid, TProtocol iprot, TProtocol oprot) throws TException;
    }

    private Iface iface_;
    protected final HashMap<String,ProcessFunction> processMap_ = new HashMap<String,ProcessFunction>();

    public boolean process(TProtocol iprot, TProtocol oprot) throws TException
    {
      TMessage msg = iprot.readMessageBegin();
      ProcessFunction fn = processMap_.get(msg.name);
      if (fn == null) {
        TProtocolUtil.skip(iprot, TType.STRUCT);
        iprot.readMessageEnd();
        TApplicationException x = new TApplicationException(TApplicationException.UNKNOWN_METHOD, "Invalid method name: '"+msg.name+"'");
        oprot.writeMessageBegin(new TMessage(msg.name, TMessageType.EXCEPTION, msg.seqid));
        x.write(oprot);
        oprot.writeMessageEnd();
        oprot.getTransport().flush();
        return true;
      }
      fn.process(msg.seqid, iprot, oprot);
      return true;
    }

    private class getServiceStats implements ProcessFunction {
      public void process(int seqid, TProtocol iprot, TProtocol oprot) throws TException
      {
        getServiceStats_args args = new getServiceStats_args();
        args.read(iprot);
        iprot.readMessageEnd();
        getServiceStats_result result = new getServiceStats_result();
        result.success = iface_.getServiceStats(args.server);
        oprot.writeMessageBegin(new TMessage("getServiceStats", TMessageType.REPLY, seqid));
        result.write(oprot);
        oprot.writeMessageEnd();
        oprot.getTransport().flush();
      }

    }

    private class ping implements ProcessFunction {
      public void process(int seqid, TProtocol iprot, TProtocol oprot) throws TException
      {
        ping_args args = new ping_args();
        args.read(iprot);
        iprot.readMessageEnd();
        ping_result result = new ping_result();
        iface_.ping();
        oprot.writeMessageBegin(new TMessage("ping", TMessageType.REPLY, seqid));
        result.write(oprot);
        oprot.writeMessageEnd();
        oprot.getTransport().flush();
      }

    }

    private class getLogSince implements ProcessFunction {
      public void process(int seqid, TProtocol iprot, TProtocol oprot) throws TException
      {
        getLogSince_args args = new getLogSince_args();
        args.read(iprot);
        iprot.readMessageEnd();
        getLogSince_result result = new getLogSince_result();
        result.success = iface_.getLogSince(args.server, args.bucket, args.lsn, args.kbLimit);
        oprot.writeMessageBegin(new TMessage("getLogSince", TMessageType.REPLY, seqid));
        result.write(oprot);
        oprot.writeMessageEnd();
        oprot.getTransport().flush();
      }

    }

  }

  public static class getServiceStats_args implements TBase, java.io.Serializable, Cloneable, Comparable<getServiceStats_args>   {
    private static final TStruct STRUCT_DESC = new TStruct("getServiceStats_args");
    private static final TField SERVER_FIELD_DESC = new TField("server", TType.STRING, (short)1);

    public String server;
    public static final int SERVER = 1;

    // isset id assignments

    public static final Map<Integer, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new HashMap<Integer, FieldMetaData>() {{
      put(SERVER, new FieldMetaData("server", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.STRING)));
    }});

    static {
      FieldMetaData.addStructMetaDataMap(getServiceStats_args.class, metaDataMap);
    }

    public static final Map<String, Integer> fieldNameMap = Collections.unmodifiableMap(new HashMap<String, Integer>() {{
      put("server", new Integer(SERVER));
    }});

    public getServiceStats_args() {
    }

    public getServiceStats_args(
      String server)
    {
      this();
      this.server = server;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getServiceStats_args(getServiceStats_args other) {
      if (other.isSetServer()) {
        this.server = other.server;
      }
    }

    public getServiceStats_args deepCopy() {
      return new getServiceStats_args(this);
    }

    @Deprecated
    public getServiceStats_args clone() {
      return new getServiceStats_args(this);
    }

    public String getServer() {
      return this.server;
    }

    public getServiceStats_args setServer(String server) {
      this.server = server;
      return this;
    }

    public void unsetServer() {
      this.server = null;
    }

    // Returns true if field server is set (has been asigned a value) and false otherwise
    public boolean isSetServer() {
      return this.server != null;
    }

    public void setServerIsSet(boolean value) {
      if (!value) {
        this.server = null;
      }
    }

    public void setFieldValue(int fieldID, Object value) {
      switch (fieldID) {
      case SERVER:
        if (value == null) {
          unsetServer();
        } else {
          setServer((String)value);
        }
        break;

      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    public Object getFieldValue(int fieldID) {
      switch (fieldID) {
      case SERVER:
        return getServer();

      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise
    public boolean isSet(int fieldID) {
      switch (fieldID) {
      case SERVER:
        return isSetServer();
      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getServiceStats_args)
        return this.equals((getServiceStats_args)that);
      return false;
    }

    public boolean equals(getServiceStats_args that) {
      if (that == null)
        return false;

      boolean this_present_server = true && this.isSetServer();
      boolean that_present_server = true && that.isSetServer();
      if (this_present_server || that_present_server) {
        if (!(this_present_server && that_present_server))
          return false;
        if (!this.server.equals(that.server))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getServiceStats_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getServiceStats_args typedOther = (getServiceStats_args)other;

      lastComparison = Boolean.valueOf(isSetServer()).compareTo(isSetServer());
      if (lastComparison != 0) {
        return lastComparison;
      }
      lastComparison = TBaseHelper.compareTo(server, typedOther.server);
      if (lastComparison != 0) {
        return lastComparison;
      }
      return 0;
    }

    public void read(TProtocol iprot) throws TException {
      TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case SERVER:
            if (field.type == TType.STRING) {
              this.server = iprot.readString();
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public void write(TProtocol oprot) throws TException {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (this.server != null) {
        oprot.writeFieldBegin(SERVER_FIELD_DESC);
        oprot.writeString(this.server);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getServiceStats_args(");
      boolean first = true;

      sb.append("server:");
      if (this.server == null) {
        sb.append("null");
      } else {
        sb.append(this.server);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

  public static class getServiceStats_result implements TBase, java.io.Serializable, Cloneable   {
    private static final TStruct STRUCT_DESC = new TStruct("getServiceStats_result");
    private static final TField SUCCESS_FIELD_DESC = new TField("success", TType.MAP, (short)0);

    public Map<String,Long> success;
    public static final int SUCCESS = 0;

    // isset id assignments

    public static final Map<Integer, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new HashMap<Integer, FieldMetaData>() {{
      put(SUCCESS, new FieldMetaData("success", TFieldRequirementType.DEFAULT, 
          new MapMetaData(TType.MAP, 
              new FieldValueMetaData(TType.STRING), 
              new FieldValueMetaData(TType.I64))));
    }});

    static {
      FieldMetaData.addStructMetaDataMap(getServiceStats_result.class, metaDataMap);
    }

    public static final Map<String, Integer> fieldNameMap = Collections.unmodifiableMap(new HashMap<String, Integer>() {{
      put("success", new Integer(SUCCESS));
    }});

    public getServiceStats_result() {
    }

    public getServiceStats_result(
      Map<String,Long> success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getServiceStats_result(getServiceStats_result other) {
      if (other.isSetSuccess()) {
        Map<String,Long> __this__success = new HashMap<String,Long>();
        for (Map.Entry<String, Long> other_element : other.success.entrySet()) {

          String other_element_key = other_element.getKey();
          Long other_element_value = other_element.getValue();

          String __this__success_copy_key = other_element_key;

          Long __this__success_copy_value = other_element_value;

          __this__success.put(__this__success_copy_key, __this__success_copy_value);
        }
        this.success = __this__success;
      }
    }

    public getServiceStats_result deepCopy() {
      return new getServiceStats_result(this);
    }

    @Deprecated
    public getServiceStats_result clone() {
      return new getServiceStats_result(this);
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    public void putToSuccess(String key, long val) {
      if (this.success == null) {
        this.success = new HashMap<String,Long>();
      }
      this.success.put(key, val);
    }

    public Map<String,Long> getSuccess() {
      return this.success;
    }

    public getServiceStats_result setSuccess(Map<String,Long> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    // Returns true if field success is set (has been asigned a value) and false otherwise
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(int fieldID, Object value) {
      switch (fieldID) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Map<String,Long>)value);
        }
        break;

      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    public Object getFieldValue(int fieldID) {
      switch (fieldID) {
      case SUCCESS:
        return getSuccess();

      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise
    public boolean isSet(int fieldID) {
      switch (fieldID) {
      case SUCCESS:
        return isSetSuccess();
      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getServiceStats_result)
        return this.equals((getServiceStats_result)that);
      return false;
    }

    public boolean equals(getServiceStats_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public void read(TProtocol iprot) throws TException {
      TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case SUCCESS:
            if (field.type == TType.MAP) {
              {
                TMap _map0 = iprot.readMapBegin();
                this.success = new HashMap<String,Long>(2*_map0.size);
                for (int _i1 = 0; _i1 < _map0.size; ++_i1)
                {
                  String _key2;
                  long _val3;
                  _key2 = iprot.readString();
                  _val3 = iprot.readI64();
                  this.success.put(_key2, _val3);
                }
                iprot.readMapEnd();
              }
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public void write(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);

      if (this.isSetSuccess()) {
        oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
        {
          oprot.writeMapBegin(new TMap(TType.STRING, TType.I64, this.success.size()));
          for (Map.Entry<String, Long> _iter4 : this.success.entrySet())
          {
            oprot.writeString(_iter4.getKey());
            oprot.writeI64(_iter4.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getServiceStats_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

  public static class ping_args implements TBase, java.io.Serializable, Cloneable, Comparable<ping_args>   {
    private static final TStruct STRUCT_DESC = new TStruct("ping_args");

    public static final Map<Integer, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new HashMap<Integer, FieldMetaData>() {{
    }});

    static {
      FieldMetaData.addStructMetaDataMap(ping_args.class, metaDataMap);
    }

    public static final Map<String, Integer> fieldNameMap = Collections.unmodifiableMap(new HashMap<String, Integer>() {{
    }});

    public ping_args() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ping_args(ping_args other) {
    }

    public ping_args deepCopy() {
      return new ping_args(this);
    }

    @Deprecated
    public ping_args clone() {
      return new ping_args(this);
    }

    public void setFieldValue(int fieldID, Object value) {
      switch (fieldID) {
      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    public Object getFieldValue(int fieldID) {
      switch (fieldID) {
      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise
    public boolean isSet(int fieldID) {
      switch (fieldID) {
      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof ping_args)
        return this.equals((ping_args)that);
      return false;
    }

    public boolean equals(ping_args that) {
      if (that == null)
        return false;

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(ping_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      ping_args typedOther = (ping_args)other;

      return 0;
    }

    public void read(TProtocol iprot) throws TException {
      TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public void write(TProtocol oprot) throws TException {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("ping_args(");
      boolean first = true;

      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

  public static class ping_result implements TBase, java.io.Serializable, Cloneable, Comparable<ping_result>   {
    private static final TStruct STRUCT_DESC = new TStruct("ping_result");

    public static final Map<Integer, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new HashMap<Integer, FieldMetaData>() {{
    }});

    static {
      FieldMetaData.addStructMetaDataMap(ping_result.class, metaDataMap);
    }

    public static final Map<String, Integer> fieldNameMap = Collections.unmodifiableMap(new HashMap<String, Integer>() {{
    }});

    public ping_result() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ping_result(ping_result other) {
    }

    public ping_result deepCopy() {
      return new ping_result(this);
    }

    @Deprecated
    public ping_result clone() {
      return new ping_result(this);
    }

    public void setFieldValue(int fieldID, Object value) {
      switch (fieldID) {
      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    public Object getFieldValue(int fieldID) {
      switch (fieldID) {
      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise
    public boolean isSet(int fieldID) {
      switch (fieldID) {
      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof ping_result)
        return this.equals((ping_result)that);
      return false;
    }

    public boolean equals(ping_result that) {
      if (that == null)
        return false;

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(ping_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      ping_result typedOther = (ping_result)other;

      return 0;
    }

    public void read(TProtocol iprot) throws TException {
      TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public void write(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);

      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("ping_result(");
      boolean first = true;

      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

  public static class getLogSince_args implements TBase, java.io.Serializable, Cloneable, Comparable<getLogSince_args>   {
    private static final TStruct STRUCT_DESC = new TStruct("getLogSince_args");
    private static final TField SERVER_FIELD_DESC = new TField("server", TType.STRING, (short)1);
    private static final TField BUCKET_FIELD_DESC = new TField("bucket", TType.STRING, (short)2);
    private static final TField LSN_FIELD_DESC = new TField("lsn", TType.STRING, (short)3);
    private static final TField KB_LIMIT_FIELD_DESC = new TField("kbLimit", TType.I32, (short)4);

    public String server;
    public String bucket;
    public String lsn;
    public int kbLimit;
    public static final int SERVER = 1;
    public static final int BUCKET = 2;
    public static final int LSN = 3;
    public static final int KBLIMIT = 4;

    // isset id assignments
    private static final int __KBLIMIT_ISSET_ID = 0;
    private BitSet __isset_bit_vector = new BitSet(1);

    public static final Map<Integer, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new HashMap<Integer, FieldMetaData>() {{
      put(SERVER, new FieldMetaData("server", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.STRING)));
      put(BUCKET, new FieldMetaData("bucket", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.STRING)));
      put(LSN, new FieldMetaData("lsn", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.STRING)));
      put(KBLIMIT, new FieldMetaData("kbLimit", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.I32)));
    }});

    static {
      FieldMetaData.addStructMetaDataMap(getLogSince_args.class, metaDataMap);
    }

    public static final Map<String, Integer> fieldNameMap = Collections.unmodifiableMap(new HashMap<String, Integer>() {{
      put("server", new Integer(SERVER));
      put("bucket", new Integer(BUCKET));
      put("lsn", new Integer(LSN));
      put("kbLimit", new Integer(KBLIMIT));
    }});

    public getLogSince_args() {
    }

    public getLogSince_args(
      String server,
      String bucket,
      String lsn,
      int kbLimit)
    {
      this();
      this.server = server;
      this.bucket = bucket;
      this.lsn = lsn;
      this.kbLimit = kbLimit;
      setKbLimitIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getLogSince_args(getLogSince_args other) {
      __isset_bit_vector.clear();
      __isset_bit_vector.or(other.__isset_bit_vector);
      if (other.isSetServer()) {
        this.server = other.server;
      }
      if (other.isSetBucket()) {
        this.bucket = other.bucket;
      }
      if (other.isSetLsn()) {
        this.lsn = other.lsn;
      }
      this.kbLimit = other.kbLimit;
    }

    public getLogSince_args deepCopy() {
      return new getLogSince_args(this);
    }

    @Deprecated
    public getLogSince_args clone() {
      return new getLogSince_args(this);
    }

    public String getServer() {
      return this.server;
    }

    public getLogSince_args setServer(String server) {
      this.server = server;
      return this;
    }

    public void unsetServer() {
      this.server = null;
    }

    // Returns true if field server is set (has been asigned a value) and false otherwise
    public boolean isSetServer() {
      return this.server != null;
    }

    public void setServerIsSet(boolean value) {
      if (!value) {
        this.server = null;
      }
    }

    public String getBucket() {
      return this.bucket;
    }

    public getLogSince_args setBucket(String bucket) {
      this.bucket = bucket;
      return this;
    }

    public void unsetBucket() {
      this.bucket = null;
    }

    // Returns true if field bucket is set (has been asigned a value) and false otherwise
    public boolean isSetBucket() {
      return this.bucket != null;
    }

    public void setBucketIsSet(boolean value) {
      if (!value) {
        this.bucket = null;
      }
    }

    public String getLsn() {
      return this.lsn;
    }

    public getLogSince_args setLsn(String lsn) {
      this.lsn = lsn;
      return this;
    }

    public void unsetLsn() {
      this.lsn = null;
    }

    // Returns true if field lsn is set (has been asigned a value) and false otherwise
    public boolean isSetLsn() {
      return this.lsn != null;
    }

    public void setLsnIsSet(boolean value) {
      if (!value) {
        this.lsn = null;
      }
    }

    public int getKbLimit() {
      return this.kbLimit;
    }

    public getLogSince_args setKbLimit(int kbLimit) {
      this.kbLimit = kbLimit;
      setKbLimitIsSet(true);
      return this;
    }

    public void unsetKbLimit() {
      __isset_bit_vector.clear(__KBLIMIT_ISSET_ID);
    }

    // Returns true if field kbLimit is set (has been asigned a value) and false otherwise
    public boolean isSetKbLimit() {
      return __isset_bit_vector.get(__KBLIMIT_ISSET_ID);
    }

    public void setKbLimitIsSet(boolean value) {
      __isset_bit_vector.set(__KBLIMIT_ISSET_ID, value);
    }

    public void setFieldValue(int fieldID, Object value) {
      switch (fieldID) {
      case SERVER:
        if (value == null) {
          unsetServer();
        } else {
          setServer((String)value);
        }
        break;

      case BUCKET:
        if (value == null) {
          unsetBucket();
        } else {
          setBucket((String)value);
        }
        break;

      case LSN:
        if (value == null) {
          unsetLsn();
        } else {
          setLsn((String)value);
        }
        break;

      case KBLIMIT:
        if (value == null) {
          unsetKbLimit();
        } else {
          setKbLimit((Integer)value);
        }
        break;

      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    public Object getFieldValue(int fieldID) {
      switch (fieldID) {
      case SERVER:
        return getServer();

      case BUCKET:
        return getBucket();

      case LSN:
        return getLsn();

      case KBLIMIT:
        return new Integer(getKbLimit());

      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise
    public boolean isSet(int fieldID) {
      switch (fieldID) {
      case SERVER:
        return isSetServer();
      case BUCKET:
        return isSetBucket();
      case LSN:
        return isSetLsn();
      case KBLIMIT:
        return isSetKbLimit();
      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getLogSince_args)
        return this.equals((getLogSince_args)that);
      return false;
    }

    public boolean equals(getLogSince_args that) {
      if (that == null)
        return false;

      boolean this_present_server = true && this.isSetServer();
      boolean that_present_server = true && that.isSetServer();
      if (this_present_server || that_present_server) {
        if (!(this_present_server && that_present_server))
          return false;
        if (!this.server.equals(that.server))
          return false;
      }

      boolean this_present_bucket = true && this.isSetBucket();
      boolean that_present_bucket = true && that.isSetBucket();
      if (this_present_bucket || that_present_bucket) {
        if (!(this_present_bucket && that_present_bucket))
          return false;
        if (!this.bucket.equals(that.bucket))
          return false;
      }

      boolean this_present_lsn = true && this.isSetLsn();
      boolean that_present_lsn = true && that.isSetLsn();
      if (this_present_lsn || that_present_lsn) {
        if (!(this_present_lsn && that_present_lsn))
          return false;
        if (!this.lsn.equals(that.lsn))
          return false;
      }

      boolean this_present_kbLimit = true;
      boolean that_present_kbLimit = true;
      if (this_present_kbLimit || that_present_kbLimit) {
        if (!(this_present_kbLimit && that_present_kbLimit))
          return false;
        if (this.kbLimit != that.kbLimit)
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getLogSince_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getLogSince_args typedOther = (getLogSince_args)other;

      lastComparison = Boolean.valueOf(isSetServer()).compareTo(isSetServer());
      if (lastComparison != 0) {
        return lastComparison;
      }
      lastComparison = TBaseHelper.compareTo(server, typedOther.server);
      if (lastComparison != 0) {
        return lastComparison;
      }
      lastComparison = Boolean.valueOf(isSetBucket()).compareTo(isSetBucket());
      if (lastComparison != 0) {
        return lastComparison;
      }
      lastComparison = TBaseHelper.compareTo(bucket, typedOther.bucket);
      if (lastComparison != 0) {
        return lastComparison;
      }
      lastComparison = Boolean.valueOf(isSetLsn()).compareTo(isSetLsn());
      if (lastComparison != 0) {
        return lastComparison;
      }
      lastComparison = TBaseHelper.compareTo(lsn, typedOther.lsn);
      if (lastComparison != 0) {
        return lastComparison;
      }
      lastComparison = Boolean.valueOf(isSetKbLimit()).compareTo(isSetKbLimit());
      if (lastComparison != 0) {
        return lastComparison;
      }
      lastComparison = TBaseHelper.compareTo(kbLimit, typedOther.kbLimit);
      if (lastComparison != 0) {
        return lastComparison;
      }
      return 0;
    }

    public void read(TProtocol iprot) throws TException {
      TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case SERVER:
            if (field.type == TType.STRING) {
              this.server = iprot.readString();
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case BUCKET:
            if (field.type == TType.STRING) {
              this.bucket = iprot.readString();
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case LSN:
            if (field.type == TType.STRING) {
              this.lsn = iprot.readString();
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case KBLIMIT:
            if (field.type == TType.I32) {
              this.kbLimit = iprot.readI32();
              setKbLimitIsSet(true);
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public void write(TProtocol oprot) throws TException {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (this.server != null) {
        oprot.writeFieldBegin(SERVER_FIELD_DESC);
        oprot.writeString(this.server);
        oprot.writeFieldEnd();
      }
      if (this.bucket != null) {
        oprot.writeFieldBegin(BUCKET_FIELD_DESC);
        oprot.writeString(this.bucket);
        oprot.writeFieldEnd();
      }
      if (this.lsn != null) {
        oprot.writeFieldBegin(LSN_FIELD_DESC);
        oprot.writeString(this.lsn);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(KB_LIMIT_FIELD_DESC);
      oprot.writeI32(this.kbLimit);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getLogSince_args(");
      boolean first = true;

      sb.append("server:");
      if (this.server == null) {
        sb.append("null");
      } else {
        sb.append(this.server);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("bucket:");
      if (this.bucket == null) {
        sb.append("null");
      } else {
        sb.append(this.bucket);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("lsn:");
      if (this.lsn == null) {
        sb.append("null");
      } else {
        sb.append(this.lsn);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("kbLimit:");
      sb.append(this.kbLimit);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

  public static class getLogSince_result implements TBase, java.io.Serializable, Cloneable, Comparable<getLogSince_result>   {
    private static final TStruct STRUCT_DESC = new TStruct("getLogSince_result");
    private static final TField SUCCESS_FIELD_DESC = new TField("success", TType.LIST, (short)0);

    public List<logEntry> success;
    public static final int SUCCESS = 0;

    // isset id assignments

    public static final Map<Integer, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new HashMap<Integer, FieldMetaData>() {{
      put(SUCCESS, new FieldMetaData("success", TFieldRequirementType.DEFAULT, 
          new ListMetaData(TType.LIST, 
              new StructMetaData(TType.STRUCT, logEntry.class))));
    }});

    static {
      FieldMetaData.addStructMetaDataMap(getLogSince_result.class, metaDataMap);
    }

    public static final Map<String, Integer> fieldNameMap = Collections.unmodifiableMap(new HashMap<String, Integer>() {{
      put("success", new Integer(SUCCESS));
    }});

    public getLogSince_result() {
    }

    public getLogSince_result(
      List<logEntry> success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getLogSince_result(getLogSince_result other) {
      if (other.isSetSuccess()) {
        List<logEntry> __this__success = new ArrayList<logEntry>();
        for (logEntry other_element : other.success) {
          __this__success.add(new logEntry(other_element));
        }
        this.success = __this__success;
      }
    }

    public getLogSince_result deepCopy() {
      return new getLogSince_result(this);
    }

    @Deprecated
    public getLogSince_result clone() {
      return new getLogSince_result(this);
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    public java.util.Iterator<logEntry> getSuccessIterator() {
      return (this.success == null) ? null : this.success.iterator();
    }

    public void addToSuccess(logEntry elem) {
      if (this.success == null) {
        this.success = new ArrayList<logEntry>();
      }
      this.success.add(elem);
    }

    public List<logEntry> getSuccess() {
      return this.success;
    }

    public getLogSince_result setSuccess(List<logEntry> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    // Returns true if field success is set (has been asigned a value) and false otherwise
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(int fieldID, Object value) {
      switch (fieldID) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((List<logEntry>)value);
        }
        break;

      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    public Object getFieldValue(int fieldID) {
      switch (fieldID) {
      case SUCCESS:
        return getSuccess();

      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise
    public boolean isSet(int fieldID) {
      switch (fieldID) {
      case SUCCESS:
        return isSetSuccess();
      default:
        throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
      }
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof getLogSince_result)
        return this.equals((getLogSince_result)that);
      return false;
    }

    public boolean equals(getLogSince_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(getLogSince_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      getLogSince_result typedOther = (getLogSince_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      lastComparison = TBaseHelper.compareTo(success, typedOther.success);
      if (lastComparison != 0) {
        return lastComparison;
      }
      return 0;
    }

    public void read(TProtocol iprot) throws TException {
      TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case SUCCESS:
            if (field.type == TType.LIST) {
              {
                TList _list5 = iprot.readListBegin();
                this.success = new ArrayList<logEntry>(_list5.size);
                for (int _i6 = 0; _i6 < _list5.size; ++_i6)
                {
                  logEntry _elem7;
                  _elem7 = new logEntry();
                  _elem7.read(iprot);
                  this.success.add(_elem7);
                }
                iprot.readListEnd();
              }
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public void write(TProtocol oprot) throws TException {
      oprot.writeStructBegin(STRUCT_DESC);

      if (this.isSetSuccess()) {
        oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRUCT, this.success.size()));
          for (logEntry _iter8 : this.success)
          {
            _iter8.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("getLogSince_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
