/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.thrudb.thrudex;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Analyzer implements TEnum {
  STANDARD(1),
  KEYWORD(2),
  SIMPLE(3),
  STOP(4),
  WHITESPACE(5),
  CJK(6);

  private final int value;

  private Analyzer(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Analyzer findByValue(int value) { 
    switch (value) {
      case 1:
        return STANDARD;
      case 2:
        return KEYWORD;
      case 3:
        return SIMPLE;
      case 4:
        return STOP;
      case 5:
        return WHITESPACE;
      case 6:
        return CJK;
      default:
        return null;
    }
  }
}
